@echo off
echo Cleaning old build...
rmdir /s /q build
echo Running Sphinx build...
make html
echo Moving build/html to root...
move build\html\* .
echo Deleting old build folder...
rmdir /s /q build
echo Committing changes...
git add .
git commit -m "Update Sphinx documentation"
git push origin main
echo Deployment complete!
